# CONFIG for Jekyll

# Permalinks
permalink:           pretty

# Setup
title:            GIF
tagline: >
  No need to figure out if it's pronounced as "Gif" or "Jif"
  Just add it in and enjoy
url:
baseurl:          "/gif/"
author:
- name:           Patrick Gurr
- url:            https://twitter.com/ashenheim
- email:          patrick@gmail.com


# Build
markdown: kramdown
highlighter: rouge
exclude:
- 'node_modules'
- 'bower_components'
- 'bower.json'
- 'gulpfile.js'
- 'package.json'
- 'README.md'

# compress.html by Anatol Broder (http://jch.penibelst.de)
compress_html:
  clippings: all
  comments: ["<!--", "-->"]
  endings: all
  ignore:
    envs: [local]
